Enhancement(learning-service) : Add Query Based By Who is Logged In
ayubyogabfi/learning-management-service pull request #10
Opened 2023-12-04 04:24 UTC by ayubyogabfi

2023-12-04 04:39 UTC, bfi-atria-tya requested changes

2023-12-04 04:39 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/CreateArticleResponse.java
> +@Getter
Setter Getter diapus aja

2023-12-04 04:39 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/controller/ArticleController.java
> +  ) {
token'a langsung divalidasi disini (controller) aja (buat service baru)

2023-12-04 04:39 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/controller/ArticleController.java
> +    GeneralDataPaginationResponse<ArticleResponse> response = articleService.searchArticle(request, token);
token'a langsung divalidasi disini (controller) aja (buat service baru)

2023-12-04 04:39 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/controller/SectionController.java
> +    List<Section> sections = sectionService.getAllSections(token);
token'a langsung divalidasi disini (controller) aja (buat service baru)

2023-12-04 04:39 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/repository/SectionRepository.java
> +  Optional<Section> findSectionIdOnArticleSection(String sectionId, String extractedUsername);
function ini tidak search by extractedUsername ?

2023-12-04 06:11 UTC, ayubyogabfi commented on src/main/java/com/example/demo/dto/CreateArticleResponse.java
> +@Getter
ini aku pake di ArticleServiceImpl di method createArticle, untuk map new articlenya, wdyt kak ?

2023-12-04 06:12 UTC, ayubyogabfi commented on src/main/java/com/example/demo/repository/SectionRepository.java
> +  Optional<Section> findSectionIdOnArticleSection(String sectionId, String extractedUsername);
pake kak, apa @.query nya di buat juga ?

2023-12-04 06:51 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/CreateArticleResponse.java
> +@Getter
tetep pake Builder juga ya..

2023-12-04 06:56 UTC, bfi-atria-tya requested changes

2023-12-04 06:56 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/repository/SectionRepository.java
> +  Optional<Section> findSectionIdOnArticleSection(String sectionId, String extractedUsername);
oalah, sorry2 ga ngeh ada query native'a diatas'a

2023-12-04 08:31 UTC, ayubyogabfi commented on src/main/java/com/example/demo/controller/SectionController.java
> +    List<Section> sections = sectionService.getAllSections(token);
kak buat yang ini kan ga pake parameter, apa buat dto request nya juga ?

2023-12-05 08:05 UTC, bfi-atria-tya requested changes

2023-12-05 08:05 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/impl/ArticleServiceImpl.java
> +    articleRepository.save(newArticle);
jangan lupa buat save di table tm_section'a juga ya (kalau kirim section title)

2023-12-05 08:05 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/controller/ArticleController.java
> +  ) {
ini request header & validate token'a ada dimana ?

2023-12-05 08:05 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/controller/SectionController.java
> +    List<Section> sections = sectionService.getAllSections(token);
hmm, ini langsung di validate di controller aja (bikin service baru yg act as middleware kek aku bilang kemaren)

2023-12-05 08:05 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/SectionService.java
> +  List<Section> getAllSections(String token);
jangan parsing token ke service yg isi'a logic kek gini

2023-12-05 08:05 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/ArticleService.java
> +  GeneralDataPaginationResponse<ArticleResponse> findAll(String token);
jangan parsing token ke service yg isi'a logic kek gini

2023-12-05 08:05 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/impl/ArticleServiceImpl.java
> +    String extractedUsername = JwtUtil.getSubject(request.getToken());
jangan lupa ini ditaro di controller (di wrap sama service baru, yg act as middleware)

2023-12-05 08:05 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/impl/ArticleServiceImpl.java
> +    String extractedUsername = JwtUtil.getSubject(token);
jangan lupa ini ditaro di controller (di wrap sama service baru, yg act as middleware)

2023-12-05 08:05 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/impl/SectionServiceImpl.java
> +    String extractedUsername = JwtUtil.getSubject(token);
jangan lupa buat save di table tm_section'a juga ya (kalau kirim section title)

2023-12-06 10:55 UTC, bfi-atria-tya requested changes

2023-12-06 10:55 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/entity/User.java
>  @Getter
hapus setter getter (di search all ya)

2023-12-06 10:55 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/impl/ArticleServiceImpl.java
> +    checkArticle(request.getArticleTitle(), extractedUsername); //check article already on db or not
miss: check section title

2023-12-07 01:33 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/repository/SectionRepository.java
> +  Optional<Section> findSectionOnDatabase(String sectionTitle, String extractedUsername);
sebener'a penamaan'a ga perlu ada onDatabase, tapi gpp, nanti masuk di enhancement aja

2023-12-07 01:40 UTC, bfi-atria-tya requested changes

2023-12-07 01:40 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/impl/ArticleServiceImpl.java
> +      ArticleSection articleSection = ArticleSection.builder().articleId(articleId).sectionId(sectionId).build();
ini insert'a jangan disini, td_article_section itu di insert paling terakhir

2023-12-07 01:40 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/impl/ArticleServiceImpl.java
> +      Optional<Article> articles = articleRepository.findArticleOnDatabase(articleTitle, extractedUsername);
kenapa ada query get article disini ?

2023-12-07 01:42 UTC, ayubyogabfi commented on src/main/java/com/example/demo/service/impl/ArticleServiceImpl.java
> +      Optional<Article> articles = articleRepository.findArticleOnDatabase(articleTitle, extractedUsername);
Ini nyambung sama yang di atas sih kak, untuk ceeate articlesection, berarti buat function baru lagi atau better masukin di function create ?

2023-12-07 03:07 UTC, bfi-atria-tya requested changes

2023-12-07 03:07 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/impl/ArticleServiceImpl.java
> +    Optional<Section> sections = sectionRepository.findSection(sectionTitle, extractedUsername);
hmm, ini jangan di query lagi, result'a ambil aja dari query yg diatas'a

2023-12-07 08:26 UTC, bfi-atria-tya requested changes

2023-12-07 08:26 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/impl/ArticleServiceImpl.java
> +    Article newArticle = Article.builder().title(request.getArticleTitle()).body(request.getBody()).build();
tambahin created attribute pada saat save (taro @Data di class Base Entity)

2023-12-07 08:26 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/impl/ArticleServiceImpl.java
> +    articleSectionRepository.save(articleSection);
tambahin created attribute pada saat save (taro @Data di class Base Entity)

2023-12-07 08:26 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/impl/ArticleServiceImpl.java
> +      sectionRepository.save(createSection);
tambahin created attribute pada saat save (taro @Data di class Base Entity)

2023-12-07 10:47 UTC, bfi-atria-tya approved these changes

2023-12-07 10:47 UTC, merged