feat(learning-service) : Add API Get Article By Keyword
ayubyogabfi/learning-management-service pull request #2
Opened 2023-11-24 00:04 UTC by ayubyogabfi

Adding feature API Get Article by Keyword
and fixing response on Get All Section Controller

2023-11-24 07:07 UTC, bfi-atria-tya requested changes

2023-11-24 07:07 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/controller/SectionController.java
> +    @GetMapping("/all-section")
path: /article-list ?

2023-11-24 07:07 UTC, bfi-atria-tya commented on src/test/java/com/example/demo/controller/ArticleControllerTest.java
> +package com.example.demo.controller;
buat test case untuk service'a, jadi skeleton test structure'a disesuaikan dengan main package'a

2023-11-24 07:07 UTC, bfi-atria-tya commented on src/test/java/com/example/demo/controller/ArticleControllerTest.java
> +
termasuk test case buat repository'a..
contoh: https://github.com/bfi-finance/bravo-bpm-service/blob/master/src/test/java/com/bfi/bravo/repository/SurveyorLevelCoverageRepositoryTest.java

2023-11-24 07:40 UTC, bfi-atria-tya requested changes

2023-11-24 07:40 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/repository/ArticleRepository.java
> +    List<Article> findByArticleTitle(String articleTitle);
ikutin sesuai query yg di design (join 3 table)

2023-11-24 10:01 UTC, bfi-atria-tya requested changes

2023-11-24 10:01 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/repository/ArticleRepository.java
> +            "OR ta.body LIKE CONCAT('%', :articleTitle, '%'))")
ini section title'a juga perlu dicari

2023-11-24 10:02 UTC, bfi-atria-tya requested changes

2023-11-24 10:02 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/controller/ArticleController.java
> +    @PostMapping("/search-article")
path'a: /learning-management-system/v1/article-list/{article-title}

2023-11-24 10:28 UTC, bfi-atria-tya requested changes

2023-11-24 10:28 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/controller/ArticleController.java
> +    @PostMapping("/learning-management-system/v1/article-list/{article-title}")
digrouping path'a ya
(dimulai dari /v1/*)

rapi'n untuk API yg lain juga

2023-11-24 10:48 UTC, bfi-atria-tya requested changes

2023-11-24 10:48 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/controller/ArticleController.java
> +@RestController
grouping sperti ini ya: https://github.com/bfi-finance/bravo-bpm-service/blob/86c0b1d3b4039a9c072ecfc1a3bb59d1b7729796/src/main/java/com/bfi/bravo/controller/v2/ApplicationLoanRestructureV2Controller.java#L24

2023-11-27 03:18 UTC, bfi-atria-tya requested changes

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/config/CommonConfig.java
> +  PasswordEncoder passwordEncoder() {
kita ada pake ini ? kalo gada, apus aja..

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/config/CommonConfig.java
> +  ModelMapper modelMapper() {
kita ada pake ini ? kalo gada, apus aja..

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/config/CommonConfig.java
> +  CommandLineRunner run(UserService userService, RoleService roleService) {
kita ada pake ini ? kalo gada, apus aja..

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/config/OpenAPIConfig.java
> +  public OpenAPI customOpenAPI(
kita ada pake ini ? kalo gada, apus aja..

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/constants/TokenConstants.java
> +  public static Algorithm getAlgorithm() {
ini pindahin ke utils

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/controller/SectionController.java
> +  @GetMapping("/v1/article-list")
/v1/article-list kek'a bisa dipindahin di @RequestMapping

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/ArticleResponse.java
> +  private String sectionTitle;
ini ga dimapping @JsonProperty(value = 'nama field') ?

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/ArticleResponse.java
> +  private String articleTitle;
ini ga dimapping @JsonProperty(value = 'nama field') ?

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/ArticleResponse.java
> +  private String body;
ini ga dimapping @JsonProperty(value = 'nama field') ?

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/ErrorResponse.java
> +  private Instant timestamp;
ini ga dimapping @JsonProperty(value = 'nama field') ?

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/ErrorResponse.java
> +  private int status;
ini ga dimapping @JsonProperty(value = 'nama field') ?

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/ErrorResponse.java
> +  private String reason;
ini ga dimapping @JsonProperty(value = 'nama field') ?

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/ErrorResponse.java
ini ga dimapping @JsonProperty(value = 'nama field') ?

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/ErrorResponse.java
> +  private String type;
ini ga dimapping @JsonProperty(value = 'nama field') ?

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/ErrorResponse.java
> +  private String path;
ini ga dimapping @JsonProperty(value = 'nama field') ?

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/ErrorResponse.java
> +  private String message;
ini ga dimapping @JsonProperty(value = 'nama field') ?

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/SearchArticleRequest.java
> +  private String articleTitle;
ini ga dimapping @JsonProperty(value = 'nama field') ?

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/SectionResponseData.java
>  public class SectionResponseData {
pake @Builder aja, instead of Setter Getter

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/SectionResponses.java
> +  public SectionResponses(List<T> data) {
pake @builder aja, instead of Setter Getter

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/UserDto.java
> +  @JsonProperty(required = true)
jangan lupa isi value'a juga -> @JsonProperty(value = 'nama field')

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/UserDto.java
> +  @JsonProperty(required = true)
jangan lupa isi value'a juga -> @JsonProperty(value = 'nama field')

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/UserDto.java
> +  @JsonProperty(required = true)
jangan lupa isi value'a juga -> @JsonProperty(value = 'nama field')

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/UserDto.java
> +  @JsonProperty(required = true)
jangan lupa isi value'a juga -> @JsonProperty(value = 'nama field')

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/entity/ArticleSection.java
> +  public String section_id;
seragamin untuk define annotation @Column(name = "column name")
dan untuk variable, tetap harus  camel case ya (karna Java pattern)

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/entity/ArticleSection.java
> +  public String article_id;
seragamin untuk define annotation @Column(name = "column name")
dan untuk variable, tetap harus  camel case ya (karna Java pattern)

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/entity/ArticleSection.java
> +  public String body;
seragamin untuk define annotation @Column(name = "column name")

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/entity/Role.java
>  public class Role extends BaseEntity {
karna kita gada role, jadi semua code yg berhubungan dengan role, itu diapus aja ya

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/entity/User.java
> +  public List<String> getRolesName() {
karna kita ga pake role, jadi semua yg berhubungan dgn role itu diapus aja ya..

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/repository/ArticleRepository.java
> +  List<ArticleResponse> findByArticleTitle(@Param("articleTitle") String articleTitle);
nama function'a sesuaikan dgn query'a ya

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/repository/RoleRepository.java
> +  Optional<Role> findByName(String name);
karna kita gada role, jadi semua code yg berhubungan dengan role, itu diapus aja ya

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/repository/UserRepository.java
>  public interface UserRepository extends JpaRepository<User, Integer> {
query untuk pengecekan username & password, itu dimana ya ?

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/RoleService.java
>  public class RoleService {
karna kita gada role, jadi semua code yg berhubungan dengan role, itu diapus aja ya

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/UserService.java
> +  public void addRoleByUserId(Integer userId, String roleName) {
karna kita gada role, jadi semua code yg berhubungan dengan role, itu diapus aja ya

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/UserService.java
> +  public void addRoleByUsername(String username, String roleName) {
karna kita gada role, jadi semua code yg berhubungan dengan role, itu diapus aja ya

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/util/JwtUtil.java
> +  public static Boolean verify(String token) {
jangan lupa dipake verify'a ya di semua API

2023-11-27 03:18 UTC, bfi-atria-tya commented on src/test/java/com/example/demo/service/UserServiceTest.java
>  import com.example.demo.exceptions.ConflictException;
test case for UserController & Repository'a jangan lupa ya

2023-11-27 03:22 UTC, bfi-atria-tya requested changes

2023-11-27 03:22 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/controller/UserController.java
>  @RequestMapping(path = APIConstants.USERS_PATH, produces = APPLICATION_JSON_VALUE)
jangan lupa update'n URL login & registration (sesuai yg di design ya)

2023-11-27 04:16 UTC, ayubyogabfi commented on src/main/java/com/example/demo/config/OpenAPIConfig.java
> +  public OpenAPI customOpenAPI(
aku pake buat info app nya aja sih sama di atas buat auth nya, atau ada saran lain kak ?

2023-11-27 09:04 UTC, bfi-atria-tya requested changes

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/config/SecurityConfig.java
>  public class SecurityConfig extends WebSecurityConfigurerAdapter {
masih pake WebSecurityConfigurerAdapter (deprecated) ?

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/controller/SectionController.java
> +  private final SectionService sectionService;
ini knapa ga pake interface ?

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/controller/LoginController.java
> +    private final LoginService loginService;
kenapa harus pake final ?

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/ArticleService.java
> +public class ArticleService {
ini knapa ga pake interface ?

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/LoginService.java
> +package com.example.demo.service;
ini knapa ga pake interface ?

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/RoleService.java
>  import com.example.demo.entity.Role;
karna kita gada role, jadi semua code yg berhubungan dengan role, itu diapus aja ya

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/UserService.java
>  public class UserService implements UserDetailsService {
UserDetailsService boleh dipindah ke package service?

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/controller/UserController.java
> +  public ResponseEntity<Collection<User>> findAll() {
endpoint ini hapus aja

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/LoginRequest.java
> +    @JsonProperty(required = true)
seragamin @JsonProperty nya isi nama kolomnya

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/LoginRequest.java
> +    @JsonProperty(required = true)
seragamin @JsonProperty nya isi nama kolomnya

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/RoleDto.java
>  package com.example.demo.dto;
kita kan ga pake role, jadi ini apus aja..

tolong bersihkan unused code ya, terutama yg role

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/RoleDto.java
> +  @JsonProperty(required = true)
seragamin @JsonProperty nya isi nama kolomnya

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/LoginRequest.java
> +    @JsonProperty(required = true)
seragamin @JsonProperty nya isi nama kolomnya

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/LoginRequest.java
> +    @JsonProperty(required = true)
seragamin @JsonProperty nya isi nama kolomnya

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/entity/Article.java
> +  private String sectionTitle;
seragamin untuk define annotation @Column(name = "column name")

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/entity/Article.java
> +  private String articleTitle;
seragamin untuk define annotation @Column(name = "column name")

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/entity/Article.java
> +  private String body;
seragamin untuk define annotation @Column(name = "column name")

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/entity/Role.java
>  package com.example.demo.entity;
karna kita gada role, jadi semua code yg berhubungan dengan role, itu diapus aja ya

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/entity/User.java
> +  @Column
seragamin untuk define annotation di @column(), isi name-nya..
kalo ada tambahan parameter, boleh..

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/entity/User.java
> +  @Column(unique = true)
seragamin untuk define annotation di @column(), isi name-nya..
kalo ada tambahan parameter, boleh..

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/entity/User.java
> +  @Column(unique = true)
seragamin untuk define annotation di @column(), isi name-nya..
kalo ada tambahan parameter, boleh..

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/entity/User.java
> +  @Column(nullable = false)
seragamin untuk define annotation di @column(), isi name-nya..
kalo ada tambahan parameter, boleh..

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/entity/User.java
> +  @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
seragamin untuk define annotation di @column(), isi name-nya..
kalo ada tambahan parameter, boleh..

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/repository/RoleRepository.java
>  package com.example.demo.repository;
karna kita ga pake role, jadi ini dihapus aja

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/LoginService.java
> +        Authentication authentication = authenticationManager.authenticate(authenticationToken);
apakah tidak menambahkan pengecekan dari DB ?

2023-11-27 09:04 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/RoleService.java
>  import com.example.demo.entity.Role;
karna kita ga pake role, jadi ini dihapus aja

2023-11-28 02:15 UTC, bfi-atria-tya requested changes

2023-11-28 02:15 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/config/OpenAPIConfig.java
> +  //i use this
kasih deskripsi yg deskriptif

2023-11-28 02:15 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/entity/Role.java
> +import java.util.Objects;
file ini dihapus aja, karna ga dipake

2023-11-28 02:15 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/repository/ArticleRepository.java
> +  List<ArticleResponse> findArticleByArticleTitle(@Param("articleTitle") String articleTitle);
ini parameter'a harus'a bukan articleTitle (ini untuk API Search article by keyword ya)

2023-11-28 02:15 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/service/impl/UserDetailsImpl.java
> +public class UserDetailsImpl extends User {
kalo aku lihat penggunaan'a, ini jatuh'a untuk Entity (?)

2023-11-28 06:41 UTC, bfi-atria-tya requested changes

2023-11-28 06:41 UTC, bfi-atria-tya commented on src/main/java/com/example/demo/dto/LoginResponse.java
> +  @JsonIgnore
ini @JsonIgnore ?

2023-11-28 06:45 UTC, bfi-atria-tya approved these changes

2023-11-28 06:45 UTC, merged